### ISSUE TITLE
Emphasis public/private api distinction

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#171]
We want to clarify the public api, which consists of the module api and the public ignition object.

## TODO

- [x] https://github.com/NomicFoundation/ignition/pull/173
- [x] https://github.com/NomicFoundation/ignition/pull/174
- [x] https://github.com/NomicFoundation/ignition/pull/175
- [x] https://github.com/NomicFoundation/ignition/pull/176
- [x] https://github.com/NomicFoundation/ignition/pull/179
- [x] https://github.com/NomicFoundation/ignition/pull/180
- [x] https://github.com/NomicFoundation/ignition/pull/181
- [x] https://github.com/NomicFoundation/ignition/pull/184
- [x] https://github.com/NomicFoundation/ignition/pull/182
- [x] Simplify API and tsdocs usage with `unknown` types
- [ ] https://github.com/NomicFoundation/ignition/issues/192
- [ ] ~Look again at deploy options - check different constructors make sense and all options are needed~
- [ ] ~Clarify types and code exported to support implementing journal (clean up old journal types)~

**Comment by kanej** [comment]
This part of the refactoring is complete.
