### ISSUE TITLE
Formalise the plan and ui update api

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#192]
Our public api around `buildModule` and the `IDeploymentBuilder` are relatively constrained, however to support the cli UI and the html generation of the plan we expose most of the internal state used by Ignition-core.

We want to place an intermediary representation between the internals of Ignition-core (i.e. the `DeployState`) and other packages through `plan` and `updateUi`.

Part of #171 

## TODO

1. [ ] Determine if the same representation can be used for both plan and the UI update
2. [ ] Add an intermediary representation to the public api for the plan result
3. [ ] Add an intermediary representation to the public api for the update ui state
4. [ ] Document the api changes

**Comment by kanej** [comment]
I am closing this as the replacement intermediary approach takes us in a different direction.
