### ISSUE TITLE
Enhance module api

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#205]
> NOTE: This issue is a placeholder for the overall feature and will be used to organise the subissues.

We intend to improve the usability and discoverability of the Module API, switching to a more future orientated approach.

The module api also needs to be consumable via deploy in a way that supports typescript.

## TODO

- [ ] https://github.com/NomicFoundation/ignition/issues/204
- [x] #207
- [ ] https://github.com/NomicFoundation/ignition/issues/156
- [ ] https://github.com/NomicFoundation/ignition/issues/154
- [ ] https://github.com/NomicFoundation/ignition/issues/170
- [ ] https://github.com/NomicFoundation/ignition/issues/114
- [ ] https://github.com/NomicFoundation/ignition/issues/112
- [ ] https://github.com/NomicFoundation/ignition/issues/89
- [ ] https://github.com/NomicFoundation/ignition/issues/86
