### ISSUE TITLE
Alpha v0.1.0 Checklist

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#244]
This is a placeholder to organise subtasks for the our Public Beta of Ignition.

This checklist is a highlevel overview of our milestone: https://github.com/NomicFoundation/ignition/milestone/10

## TODO

* [x] https://github.com/NomicFoundation/ignition/issues/204
* [x] #245
* [x] https://github.com/NomicFoundation/ignition/issues/243
* [x] #258
* [x] #248
* [x] #249
* [x] https://github.com/NomicFoundation/ignition/issues/109
* [x] #297
* [x] #251
* [x] #250
* [x] #340
* [x] #341
