### ISSUE TITLE
Show UI during execution

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#259]
The previous cli ui was based on react ink. We want to bring it back. However we do not want to expose the entire internal execution state.

The initial idea is to inject an event emitter into the deploy process that the UI listens to (is this just the journal?). The UI builds up its own ui view orientated version of the current state and renders it with react ink. We suspect we can bring back alot of the previous react ink code (see older commits before it was removed to keep eslint happy).

## TODO

- [x] Design for re-integrating UI react code at the command line based on events
- [x] Bring back UI components
- [x] Wire through event emitter into the deploy and execution engine
- [ ] https://github.com/NomicFoundation/ignition/issues/402
- [ ] https://github.com/NomicFoundation/ignition/issues/419
- [ ] https://github.com/NomicFoundation/ignition/issues/433
- [ ] https://github.com/NomicFoundation/ignition/issues/434

**Comment by kanej** [comment]
Closing as a duplicate of #248
