### ISSUE TITLE
Add complex transaction monitoring and recovery

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#260]
## TODO

- [x] Switch to cross batch based execution
- [x] Restart monitoring for inflight transaction
- [x] #302
- [x] #299
- [x] #300
- [x] Fix library passing
- [ ] Integration test for each case in spec doc
