### ISSUE TITLE
Replace error serialization for the journal

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#286]
Originally raised: - https://github.com/NomicFoundation/ignition/pull/279#discussion_r1244294359

We are not capturing the stack, hence we are tricking ourselves. We are really just storing the error message.

We should have a set of more specific error states rather than storing the Error.

## TODO

- [ ] Encapsulate thrown errors from onchain-dispatcher
- [ ] Add everything error for each onchain dispatcher function
- [ ] Document in types each known error and deal with it
- [ ] Which can be simulated in integration tests

**Comment by kanej** [comment]
If there is an exception we should kill the process. If it is an expected error condition we return it into a value and return it.

We should work with return values, with exceptions as not expected.

Ideally we would have a list of known coded error states (not just the generic Error object).

**Comment by kanej** [comment]
Start with: revert and hash out more iteratively.

**Comment by alcuadrado** [comment]
This has already been implemented in the development branch
