### ISSUE TITLE
future proofing journal

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#359]
There are two parts to this:

1. Determining what changes should happen to the journal type now to reduce unnecessary changes later (lets push out the time for a major version change as far as we can).
2. Given that we will have to have newer versions of the journal in the future to support inevitable new features, how best can we manage that and are there small changes we can make now that will make a multi-version world easier

Areas to discuss include best approaches to versioning the journal file, how to support multiple message sets (v1 and v2 say) in the codebase at once.

## TODO

- [x] Investigation (research/design/discussions) about making the journal future proof to avoid maintainability burdens
- [x] #322
- [x] #361
- [x] #367
- [x] Perhaps remove onhold status?
- [x] Further breakdown of tasks based on investigation

**Comment by kanej** [comment]
Out of band we discussed our approach to the journal and versioning. The conclusion was that we will put in the changes now that will support our upcoming roadmap of features in an attempt to minimize the message changes that are needed. Non-additive changes to the messages/api will be a breaking change. We do not intend to support Ignition deployments over major changes.
