### ISSUE TITLE
Public API hardening

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#360]
This is a holder task for API refactorings and changes that harden our public API in run up to the public beta

## TODO

- [x] Rename publicly exposed types to maximum user comprehension
- [x] Confirm the names of the ModuleBuilder api
- [x] Review responsibilities of Plan vs core (are we exposing too much?)
  - [x] Should ModuleConstructor be exported
