### ISSUE TITLE
Switch configurations depending on detecting of auto-mining

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#363]
Different default values for number of block confirmations should be set depending on whether an automining chain is detected.

If a user is overriding the values, these take precedence.

In the deploy function the `deployConfig` is merged with default values. At that point it should be determined if we are in an automining chain.

## Implementation details

* For hardhat and anvil: hardhat_getAutomine — Returns a boolean
* For ganache: web3_clientVersion and check if the string result includes "Ganache"

```js
if (isHardhatGetAutomineTrue) {
   return true;
}

if (isGanache) {
   return true; // This can be a false positive
}

return false;
```

We also want to add a validation on the passed in deployconfig that throws if the number of confirmations is below 1.

## TODO

- [x] Detect automining chain (local HH test node)
- [x] Rework defaults based on the check
- [x] Add validation check - 0 confirmations is an invalid value
- [x] Check the integration tests, unit tests and examples for config overrides that are no longer required
