### ISSUE TITLE
add chain id reconciliation through the start-run message

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#367]
A deployment can only ever be run on one chain. We do not currently enforce this.

The proposed approach is to enhance the `start-run` message by adding a chainId property. Then enhance reconciliation to check whether the current chainId matches the last chainId. This likely means that the `start-run` message should update a top level property in the execution state - a fun refactoring.

## TODO

- [x] add chainId to `start-run` message
- [x] refactor the state passed into the executionStateReducer to be `{chainId: string, executionStates: ExecutionStateMap}`
- [x] add reconciliation rule
- [ ] add integration test to confirm we halt if running a deployment on a different chain

**Comment by kanej** [comment]
This requires an integration test.
