### ISSUE TITLE
Journal message cleanups

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#376]
The journal message types need several refactors:

## TODO

- [x] Move execution type guards that are about journal messages into the journal type-guards
- [x] Convert message types
- [x] Split out journal/types and journal/type-guards into smaller files
