### ISSUE TITLE
Refactor plan return type

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#450]
Make plan return results similar to deploy. The intention here is to support rerunning plan after a deployment run and getting a visual indication of progress by adding type changes in the public api now.

## TODO

- [ ] Rename plan to `visualize` (or show)?
- [ ] Change the result type to match as much of deploy as makes sense (validation fails, reconciliation fails, execution results)
- [ ] After the plan result types have been recorded we want to review the names of the serialization types, and whether we can drop additional information (like chainId)

As a follow on we intend to enhance the plan features to support showing execution information, this is captured in #449.
