### ISSUE TITLE
Rename futures after overload

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#468]
This should be follow on from the module builder overload changes.

With overloads in place we want to change the names of some of the futures. The base future name will be the one for the version that takes an artifact, the named version will be the derived one, so:

* ArtifactContractDeploymentFuture => ContractDeploymentFuture
* NamedContractDeploymentFuture => NamedContractDeploymentFuture

The same will happen for the other pairs with named variants

## TODO

- [ ] ArtifactContractDeploymentFuture/NamedContractDeploymentFuture
- [ ] ArtifactLibraryDeploymentFuture/NamedLibraryDeploymentFuture
- [ ] ArtifactContractAtFuture/NamedContractAtFuture

**Comment by alcuadrado** [comment]
I'm not sure if I understand the list in todo, but to clarify, this is the complete list in my mind:

* [ ] Rename `NamedContractDeploymentFuture` to `NamedArtifactContractDeploymentFuture`
* [ ] Rename `ArtifactContractDeploymentFuture` to `ContractDeploymentFuture`
* [ ] Rename `NamedLibraryDeploymentFuture` to `NamedArtifactLibraryDeploymentFuture`
* [ ] Rename `ArtifactLibraryDeploymentFuture` to `LibraryDeploymentFuture`
* [ ] Rename `NamedContractCallFuture` to `ContractCallFuture`
* [ ] Rename `NamedStaticCallFuture` to `StaticCallFuture`
* [ ] Rename `NamedContractAtFuture` to `NamedArtifactContractAtFuture`
* [ ] Rename `ArtifactContractAtFuture` to `ContractAtFuture`
* [ ] Rename the `FutureType` values to match the new names.
 
The idea is that the simpler name is used in the general case (you pass whichever artifact you want), and the `NamedArtifact` ones are special cases.
