### ISSUE TITLE
Manual Test Doc

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/ignition#94]
# Manual Test Doc

> To knock off the rough edges

We are doing manual testing. The outcome should be a set of new issues for enhancements, a manual test doc (under `./docs`) and potentially some new examples

## Potential Tests

* [ ] try and deploy a module that doesn’t exist
* [ ] try and plan a module that doesn't exist
* [ ] try and plan a module where the dep doesn't exist
* [ ] try and deploy after node_modules has been deleted

## Run through on networks and testnets

* [x] Sepolia
* [ ] Polygon
* [x] Optimism
* [ ] Arbitrum

## Potential further examples

* [ ] gnosis safe
* [ ] Compound
* [ ] Curve
* [ ] Balancer
* [ ] Synthetix
* Maybe look at moneylegos for other things people are testing against: https://github.com/studydefi/money-legos
* Look at hardhat-deploy feature set and tests

## TODO

* [x] Investigate which ethereum test nets and deploy to them [Morgan]
* [ ] Investigate which evm compatible L1s and L2s to test against [John]
* [ ] Try doing checkpoint and revert tests in hardhat using ignition
* [ ] Try and run an openzeppelin upgradeable contracts
* [ ] Try and run hardhat tests with ignition in a cli situation
* [ ] Try and automate a testnet deploy via github tasks
